clear all;
close all;
clc;
pkg load image;
l=im2double(imread('tiger.jpg'));
f1=fft(1);
f2=fftshift(f1);
subplot(2,2,1);
imshow(abs(f1));
title('Frequency Spectrum');
subplot(2,2,2);
imshow(abs(f2));
title('Centered Spectrum');
f3=log(1+abs(f2));
subplot(2,2,3);
imshow(f3);
title('log(1+abs(f2))');
l=fft2(f1);
ll=real(1);
subplot(2,2,4);
imshow(11);
title('2-D FFT');